name: 'Update'

on:
  workflow_dispatch:
  schedule:
    - cron: 30 10 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this based on your project

    - name: Run Python script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        VIBER_BOT_KEY: ${{ secrets.VIBER_BOT_KEY }}
        URL: ${{ secrets.URL }}
      run: |
        python bot.py  # Adjust this based on your script
